=== zedd0462/XMLProjectFinModule/app/gestion_train.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="gestion_trains">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="admins"/>
        <xs:element ref="utilisateurs"/>
        <xs:element ref="classes"/>
        <xs:element ref="gares"/>
        <xs:element ref="voyages"/>
        <xs:element ref="tickets"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="utilisateurs">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="utilisateur" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="voyages">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="voyage" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="classes">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="classe" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="gares">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="gare" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="tickets">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ticket" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="utilisateur">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="password"/>
        <xs:element ref="nom"/>
        <xs:element ref="prenom"/>
        <xs:element ref="cin"/>
      </xs:sequence>
      <xs:attribute name="username" type="xs:ID" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="password" type="xs:string"/>
  <xs:element name="nom" type="xs:string"/>
  <xs:element name="prenom" type="xs:string"/>
  <xs:element name="cin" type="xs:string"/>

  <xs:element name="voyage">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="date_dep"/>
        <xs:element ref="heure_dep"/>
        <xs:element ref="num_train"/>
        <xs:element ref="prix"/>
      </xs:sequence>
      <xs:attribute name="id_voyage" type="xs:ID" use="required"/>
      <xs:attribute name="gare_depart" type="xs:IDREF" use="required"/>
      <xs:attribute name="gare_arrive" type="xs:IDREF" use="required"/>
      <xs:attribute name="id_classe" type="xs:IDREF" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="date_dep" type="xs:string"/>
  <xs:element name="heure_dep" type="xs:string"/>
  <xs:element name="num_train" type="xs:string"/>
  <xs:element name="prix" type="xs:string"/>

  <xs:element name="classe">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nom_classe"/>
      </xs:sequence>
      <xs:attribute name="id_classe" type="xs:ID" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="nom_classe" type="xs:string"/>

  <xs:element name="gare">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nom_gare"/>
        <xs:element ref="ville"/>
      </xs:sequence>
      <xs:attribute name="id_gare" type="xs:ID" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="nom_gare" type="xs:string"/>
  <xs:element name="ville" type="xs:string"/>

  <xs:element name="ticket">
    <xs:complexType>
      <xs:attribute name="id_ticket" type="xs:ID" use="required"/>
      <xs:attribute name="username" type="xs:IDREF" use="required"/>
      <xs:attribute name="id_voyage" type="xs:IDREF" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="admins">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="admin" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="admin">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="password"/>
      </xs:sequence>
      <xs:attribute name="username" type="xs:ID" use="required"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== zedd0462/XMLProjectFinModule/app/gestion_train.xml
<?xml version="1.0" encoding="UTF-8"?>
<gestion_trains xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="gestion_train.xsd">
    <admins>
        <admin username="admin">
            <password>admin</password>
        </admin>
    </admins>
    <utilisateurs>
        <utilisateur username="fadelabdelhamid">
            <password>fadel69420</password>
            <nom>Fadel</nom>
            <prenom>Abdelhamid</prenom>
            <cin>M623182</cin>
        </utilisateur>
        <utilisateur username="user69">
            <password>pwdpwdpwd</password>
            <nom>John </nom>
            <prenom>Smith</prenom>
            <cin>D2020205</cin>
        </utilisateur>
    </utilisateurs>
    <classes>
        <classe id_classe="A">
            <nom_classe>Classe A</nom_classe>
        </classe>
        <classe id_classe="B">
            <nom_classe>Classe B</nom_classe>
        </classe>
    </classes>
    <gares>
        <gare id_gare="g001">
            <nom_gare>Gare de Safi</nom_gare>
            <ville>Safi</ville>
        </gare>
        <gare id_gare="g002">
            <nom_gare>Gare d'El Jadida</nom_gare>
            <ville>El Jadida</ville>
        </gare>
        <gare id_gare="g003">
            <nom_gare>Casa Voyageurs</nom_gare>
            <ville>Casablanca</ville>
        </gare>
        <gare id_gare="g004">
            <nom_gare>Gare de Fes</nom_gare>
            <ville>Fes</ville>
        </gare>
    <gare id_gare="g106585467065"><nom_gare/><ville>Rabat</ville></gare></gares>
    <voyages>
        <voyage id_voyage="v001" gare_depart="g001" gare_arrive="g003" id_classe="A">
            <date_dep>01-03-2024</date_dep>
            <heure_dep>08:00</heure_dep>
            <num_train>01</num_train>
            <prix>70.00</prix>
        </voyage>
        <voyage id_voyage="v002" gare_depart="g001" gare_arrive="g003" id_classe="B">
            <date_dep>01-03-2024</date_dep>
            <heure_dep>10:00</heure_dep>
            <num_train>02</num_train>
            <prix>60.00</prix>
        </voyage>
        <voyage id_voyage="v003" gare_depart="g001" gare_arrive="g003" id_classe="A">
            <date_dep>01-03-2024</date_dep>
            <heure_dep>12:00</heure_dep>
            <num_train>03</num_train>
            <prix>70.00</prix>
        </voyage>
        <voyage id_voyage="v004" gare_depart="g001" gare_arrive="g003" id_classe="B">
            <date_dep>01-03-2024</date_dep>
            <heure_dep>14:00</heure_dep>
            <num_train>04</num_train>
            <prix>60.00</prix>
        </voyage>
        <voyage id_voyage="v005" gare_depart="g001" gare_arrive="g003" id_classe="A">
            <date_dep>01-03-2024</date_dep>
            <heure_dep>16:00</heure_dep>
            <num_train>05</num_train>
            <prix>70.00</prix>
        </voyage>
        <voyage id_voyage="v006" gare_depart="g001" gare_arrive="g003" id_classe="B">
            <date_dep>01-03-2024</date_dep>
            <heure_dep>18:00</heure_dep>
            <num_train>06</num_train>
            <prix>60.00</prix>
        </voyage>
        <voyage id_voyage="v007" gare_depart="g001" gare_arrive="g002" id_classe="A">
            <date_dep>01-03-2024</date_dep>
            <heure_dep>08:00</heure_dep>
            <num_train>01</num_train>
            <prix>50.00</prix>
        </voyage>
        <voyage id_voyage="v008" gare_depart="g001" gare_arrive="g002" id_classe="B">
            <date_dep>01-03-2024</date_dep>
            <heure_dep>10:00</heure_dep>
            <num_train>02</num_train>
            <prix>40.00</prix>
        </voyage>
        <voyage id_voyage="v009" gare_depart="g001" gare_arrive="g002" id_classe="A">
            <date_dep>01-03-2024</date_dep>
            <heure_dep>12:00</heure_dep>
            <num_train>03</num_train>
            <prix>50.00</prix>
        </voyage>
        <voyage id_voyage="v010" gare_depart="g001" gare_arrive="g002" id_classe="B">
            <date_dep>01-03-2024</date_dep>
            <heure_dep>14:00</heure_dep>
            <num_train>04</num_train>
            <prix>40.00</prix>
        </voyage>
        <voyage id_voyage="v011" gare_depart="g001" gare_arrive="g002" id_classe="A">
            <date_dep>01-03-2024</date_dep>
            <heure_dep>16:00</heure_dep>
            <num_train>05</num_train>
            <prix>50.00</prix>
        </voyage>
        <voyage id_voyage="v012" gare_depart="g001" gare_arrive="g002" id_classe="B">
            <date_dep>01-03-2024</date_dep>
            <heure_dep>18:00</heure_dep>
            <num_train>06</num_train>
            <prix>40.00</prix>
        </voyage>
        <voyage id_voyage="v013" gare_depart="g001" gare_arrive="g002" id_classe="B">
            <date_dep>01-03-2024</date_dep>
            <heure_dep>18:00</heure_dep>
            <num_train>06</num_train>
            <prix>40.00</prix>
        </voyage>
        <voyage id_voyage="v014" gare_depart="g004" gare_arrive="g002" id_classe="B">
            <date_dep>01-03-2024</date_dep>
            <heure_dep>18:00</heure_dep>
            <num_train>06</num_train>
            <prix>40.00</prix>
        </voyage>
    <voyage id_voyage="v57095358765" gare_depart="g004" gare_arrive="g001" id_classe="2"><date_dep>01-03-2024</date_dep><heure_dep>10:00</heure_dep><num_train>06</num_train><prix>40.00</prix></voyage></voyages>
    <tickets>
        <ticket id_ticket="t002" username="fadelabdelhamid" id_voyage="v011"/>
        <ticket id_ticket="t746728869601565" username="fadelabdelhamid" id_voyage="v001"/>
        <ticket id_ticket="t176281835160158" username="fadelabdelhamid" id_voyage="v008"/>
        <ticket id_ticket="t155366570465" username="fadelabdelhamid" id_voyage="v013"/>
        <ticket id_ticket="t43593560765" username="fadelabdelhamid" id_voyage="v014"/>
    <ticket id_ticket="t136256975465" username="fadelabdelhamid" id_voyage="v57095358765"/><ticket id_ticket="t125757114265" username="fadelabdelhamid" id_voyage="v014"/><ticket id_ticket="t214707108665" username="fadelabdelhamid" id_voyage="v014"/></tickets>
</gestion_trains>
